'use client';

import Link from 'next/link';
import { useState, type ReactNode } from 'react';
import { Modal, useHydrated } from '@/components/shared-ui';
import { useConsultation } from '@/components/site-shell';
import {
  ArrowUpRight, ArrowRight, ArrowDown, Check,
  Sparkles, BrainCircuit, Workflow, Cloud, ShieldCheck, Code2, LockKeyhole,
  Blocks, HeartHandshake, MessageSquareText, FileText, BarChart3,
  Database, CircleCheck, Command, Plus, Layers3, Globe2,
  Headphones, CheckCheck, CircleDot,
} from 'lucide-react';
import { faqs, services } from '@/lib/site';

const serviceIcons = { sparkles: Sparkles, brain: BrainCircuit, workflow: Workflow, cloud: Cloud, shield: ShieldCheck };
type Service = (typeof services)[number];
type Audience = 'solo' | 'sme' | 'enterprise';
const audiences: Record<Audience, { label: string; title: string; subtitle: string; tasks: { icon: typeof FileText; name: string; note: string }[]; result: string }> = {
  solo: { label: '一人公司', title: '你專注創造，AI 處理日常。', subtitle: 'YOUR PERSONAL AI TEAM', tasks: [{ icon: MessageSquareText, name: '客戶查詢', note: '整理問題・草擬回覆' }, { icon: FileText, name: '內容與文件', note: '提取重點・產生草稿' }, { icon: BarChart3, name: '營運日報', note: '彙整數據・掌握進度' }], result: '一個人，也能有一個團隊的可能。' },
  sme: { label: '中小企業', title: '少一點重複，多一點協作。', subtitle: 'YOUR CONNECTED WORKSPACE', tasks: [{ icon: Database, name: 'CRM 資料同步', note: '連接系統・減少輸入' }, { icon: Workflow, name: '跨部門工作流', note: '自動分派・追蹤審批' }, { icon: BarChart3, name: '業務數據整合', note: '彙整報表・協助決策' }], result: '讓工具彼此連接，讓團隊更有默契。' },
  enterprise: { label: '企業團隊', title: '值得信賴，才能放心擴展。', subtitle: 'YOUR ENTERPRISE FOUNDATION', tasks: [{ icon: LockKeyhole, name: '資料與存取權限', note: '分級授權・保留紀錄' }, { icon: Cloud, name: '雲端與部署', note: '持續交付・彈性擴展' }, { icon: ShieldCheck, name: '監控與維運', note: '觀測狀態・追蹤異常' }], result: '從架構到維運，支援下一階段成長。' },
};

function SectionLabel({ children, light = false }: { children: ReactNode; light?: boolean }) {
  return <p className={`section-label ${light ? 'label-light' : ''}`}><span />{children}</p>;
}

function Workspace() {
  const ready = useHydrated();
  const [audience, setAudience] = useState<Audience>('solo');
  const current = audiences[audience];
  return <div className="hero-visual">
    <div className="orbital orbital-one" aria-hidden="true" /><div className="orbital orbital-two" aria-hidden="true" /><div className="orbital-point point-one" aria-hidden="true" /><div className="orbital-point point-two" aria-hidden="true" />
    <span className="visual-coordinate coordinate-top" aria-hidden="true">INTELLIGENCE, CONNECTED.</span>
    <div className="floating-chip chip-top"><span className="chip-icon"><BrainCircuit size={18} /></span><div>你的 AI 工作夥伴<small>Built around your business</small></div><span className="online-dot" /></div>
    <div className="workspace"><div className="workspace-top"><div className="workspace-brand"><Command size={18} /><span>Hangs workspace</span></div><span className="demo-badge">概念示意</span></div><div className="workspace-body"><div className="audience-switch" aria-label="選擇工作空間示意的團隊類型">{(Object.keys(audiences) as Audience[]).map(key => <button disabled={!ready} key={key} aria-pressed={audience === key} className={audience === key ? 'selected' : ''} onClick={() => setAudience(key)}>{audiences[key].label}</button>)}</div><div aria-live="polite" aria-atomic="true" className="workspace-content" key={audience}><p className="workspace-eyebrow">{current.subtitle}</p><h3>{current.title}</h3><div className="workspace-tasks">{current.tasks.map((task, index) => <div className="workspace-task" key={task.name}><span className={`task-icon task-${index}`}><task.icon size={18} strokeWidth={1.6} /></span><div><strong>{task.name}</strong><small>{task.note}</small></div><span className="task-check"><Check size={13} /></span></div>)}</div><div className="workspace-result"><Sparkles size={15} /><span>{current.result}</span></div></div></div><div className="workspace-bottom"><span><span className="online-dot" />為你的業務而設計</span><span>HUMAN + AI <ArrowUpRight size={12} /></span></div></div>
    <div className="floating-chip chip-bottom"><span className="chip-icon navy-icon"><LockKeyhole size={17} /></span><div>你的資料，由你掌握<small>Privacy by design</small></div><ShieldCheck size={18} className="green" /></div><span className="visual-coordinate coordinate-bottom" aria-hidden="true">01 / DESIGNED FOR POSSIBILITIES</span>
  </div>;
}

export default function Home() {
  const ready = useHydrated();
  const [selectedService, setSelectedService] = useState<Service | null>(null);
  const { openConsult } = useConsultation();

  return <>
    <main id="main">
      <section className="hero" id="hero" aria-labelledby="hero-title"><div className="container hero-grid"><div className="hero-copy"><a className="hero-announcement" href="#featured"><span className="online-dot" />AI 的下一步，是你的每一步。<ArrowUpRight size={13} /></a><h1 id="hero-title">少一點繁瑣，<br /><span className="hero-highlight">多一點可能<span className="hero-period">。</span><svg viewBox="0 0 420 18" preserveAspectRatio="none" aria-hidden="true"><path d="M4 12Q203 1 414 10" /></svg></span></h1><p className="hero-description">從一人公司到企業團隊，<br className="desktop-break" />以 AI、自動化與穩健 IT，把時間還給真正重要的事。</p><div className="hero-actions"><Link className="button button-primary" href="/services">看看我們的服務<ArrowUpRight size={18} /></Link><button disabled={!ready} className="button button-secondary" onClick={() => openConsult()}>免費諮詢<ArrowRight size={17} /></button></div><div className="hero-promises"><span><Check size={14} />從真實需求出發</span><span><Check size={14} />為長遠成長而設</span></div></div><Workspace /></div><div className="container hero-bottom"><span>LESS REPETITION. MORE AMBITION.</span><a href="#trust" aria-label="向下探索實瀚科技">向下探索<ArrowDown size={14} /></a></div></section>

      <section id="trust" className="trust-strip" aria-label="實瀚科技背景"><div className="container trust-inner"><p>懂技術，更懂你的業務。<span>以經驗為基礎，讓創新踏實落地。</span></p><div className="trust-stat"><strong>15<span>+</span></strong><span>團隊成員年資</span></div><div className="trust-stat"><strong>200<span>+</span></strong><span>企業服務經驗</span></div><div className="trust-stat"><strong>2023</strong><span>實瀚科技成立</span></div><div className="trust-location"><Globe2 size={25} strokeWidth={1.3} /><span>立足香港<br /><strong>連接更多可能</strong></span></div></div></section>

      <section className="section services-section" id="services" aria-labelledby="services-title"><div className="container"><div className="section-heading"><div><SectionLabel>OUR EXPERTISE</SectionLabel><h2 id="services-title">你的挑戰，我們的出發點。</h2></div><p className="section-description">不為技術而技術。<br />從一個工作難題，到一套完整的企業解決方案。</p></div><div className="services-grid">{services.map(service => { const Icon = serviceIcons[service.icon]; return <article className="service-card" key={service.id}><div className="service-card-top"><span className="service-icon"><Icon size={25} strokeWidth={1.5} /></span><span className="service-number">{service.number}</span></div><p className="service-english">{service.english}</p><h3>{service.title}</h3><p className="service-description">{service.description}</p><div className="service-card-foot"><span>{service.features[0]}</span><button disabled={!ready} className="round-arrow" onClick={() => setSelectedService(service)} aria-label={`了解${service.title}`}><ArrowUpRight size={18} /></button></div></article>; })}</div><div className="services-note"><span><CircleDot size={14} />不確定從哪裡開始？我們先聽你的需求。</span><button disabled={!ready} className="text-link" onClick={() => openConsult()}>找到適合的方向<ArrowRight size={15} /></button></div></div></section>

      <section className="section featured-section" id="featured" aria-labelledby="featured-title"><div className="container"><div className="section-heading"><div><SectionLabel>BUILT FOR YOUR EVERYDAY</SectionLabel><h2 id="featured-title">把日常，交給更好的方法。</h2></div><span className="section-aside"><span className="online-dot" />現時主打方案</span></div><div className="featured-grid"><article className="feature-ai"><div className="feature-topline"><span className="pill"><Sparkles size={13} />一人公司・精簡團隊</span><span className="feature-index">01 / AI AT WORK</span></div><h3>你的一人公司，<br />不必一個人做所有事。</h3><p>客服、文件、內容，讓 AI 成為你的得力助手。<br />把精力留給客戶，和你真正擅長的事。</p><button disabled={!ready} className="text-link" onClick={() => setSelectedService(services[1])}>探索企業職能 AI<ArrowUpRight size={17} /></button><div className="ai-preview" aria-label="AI 知識助手概念示意"><div className="ai-preview-sidebar" aria-hidden="true"><span className="ai-logo"><Sparkles size={20} /></span><MessageSquareText size={17} /><FileText size={17} /><Database size={17} /><span className="sidebar-bottom">H</span></div><div className="ai-preview-main"><div className="ai-preview-header"><span>你的企業知識助手</span><span>概念示意</span></div><div className="chat-user">幫我整理新客戶的服務查詢。<span>你</span></div><div className="chat-ai"><span className="chat-avatar"><Sparkles size={14} /></span><div><strong>先整理，再交由你作最後決定。</strong><p>我可以根據已授權的資料，協助你：</p><ul><li><CheckCheck size={13} />歸納查詢重點與客戶需求</li><li><CheckCheck size={13} />草擬回覆，供你審核</li><li><CheckCheck size={13} />標示需要人工跟進的問題</li></ul><span className="source-tag"><FileText size={10} />參考來源 · 企業知識庫</span></div></div><div className="chat-input" aria-hidden="true"><span>從一個問題，開始更有效率的一天</span><span><ArrowUpRight size={15} /></span></div></div></div></article>
      <div className="feature-right"><article className="feature-automation"><div className="feature-topline"><span className="pill pill-dark"><Workflow size={13} />流程自動化</span><span className="feature-index">02 / CONNECT</span></div><h3>重複的流程，<br />就不必重複做。</h3><p>串接工具與數據，讓查詢、訂單和報表<br className="desktop-break" />沿著你設計的流程，自動走下一步。</p><div className="flow-visual" aria-label="查詢、自動處理、同步系統流程示意"><span><MessageSquareText size={18} /><small>客戶查詢</small></span><i /><span className="flow-center"><Workflow size={20} /><small>自動處理</small></span><i /><span><Database size={18} /><small>同步系統</small></span></div><button disabled={!ready} className="feature-corner" onClick={() => setSelectedService(services[2])} aria-label="了解流程與系統自動化"><ArrowUpRight size={21} /></button></article>
      <article className="feature-cloud"><div><span className="mini-label">03 / BUILT TO SCALE</span><h3>業務向前，<br />架構跟得上。</h3><p>雲端、DevOps 與技術維運，<br />從穩定運作，走向從容擴展。</p><button disabled={!ready} className="text-link" onClick={() => setSelectedService(services[3])}>打造穩健基礎<ArrowUpRight size={17} /></button></div><div className="cloud-visual" aria-hidden="true"><div className="cloud-halo" /><div className="server-stack"><div><span /><span /><i /></div><div><span /><span /><i /></div><div><span /><span /><i /></div></div><span className="cloud-status"><span className="online-dot" />READY TO GROW</span><Cloud className="cloud-symbol" size={31} strokeWidth={1.3} /></div></article></div></div><p className="feature-caption">每個方案，從你的實際流程開始。功能、部署及服務範圍按項目需求確認。</p></div></section>

      <section className="section why-section" id="why" aria-labelledby="why-title"><div className="container"><div className="section-heading"><div><SectionLabel>WHY HANGS</SectionLabel><h2 id="why-title">不只是交付，<br className="mobile-only" />更是值得信賴的同行。</h2></div><p className="section-description">好的技術夥伴，<br />讓你看得懂、用得好，也走得遠。</p></div><div className="why-grid">{[{ icon: Code2, title: '自主擁有，不被綁定', text: '源碼、帳號與交付文件的權責清楚約定，讓你保有選擇和持續發展的空間。', tag: 'YOUR BUSINESS. YOUR CONTROL.' }, { icon: LockKeyhole, title: '資料保密，從設計開始', text: '從資料流向、存取權限到部署方式，按你的安全要求規劃，而非事後補救。', tag: 'PRIVACY BY DESIGN.' }, { icon: HeartHandshake, title: '懂你的問題，才寫程式', text: '先了解業務流程與真正的困難，再定義解法。不堆疊功能，不讓需求迷失。', tag: 'BUSINESS BEFORE TECHNOLOGY.' }, { icon: Headphones, title: '上線之後，繼續同行', text: '提供可約定的維運、培訓與駐場支援，讓團隊接得住，系統也持續進步。', tag: 'SUPPORT BEYOND LAUNCH.' }].map((item, index) => <article className="why-card" key={item.title}><div className="why-icon"><item.icon size={25} strokeWidth={1.4} /><span>0{index + 1}</span></div><h3>{item.title}</h3><p>{item.text}</p><span className="why-tag">{item.tag}</span></article>)}</div></div></section>

      <section className="section about-section" id="about" aria-labelledby="about-title"><div className="container about-grid"><div className="about-copy"><SectionLabel>EXPERIENCE MEETS WHAT’S NEXT</SectionLabel><h2 id="about-title">技術在變，<br />把事情做好的初心不變。</h2><p>實瀚科技成立於 2023 年。團隊成員均擁有 15 年以上系統開發經驗，結合逾 200 家企業的服務經驗，深知數位轉型不只是換一套系統，而是讓業務真正向前。</p><p>我們以現代化全棧架構，連接前端體驗、業務流程與底層數據。從需求梳理、UML 架構設計到開發與維運，讓每個技術決定，都有業務上的理由。</p><a className="text-link" href="#process">了解我們如何合作<ArrowUpRight size={17} /></a><div className="about-signature"><span className="signature-line" /><span>實在解題，瀚見可能。</span><small>THE HANGS APPROACH</small></div></div><div className="architecture-panel"><div className="architecture-heading"><span><Layers3 size={17} />為長遠而設的技術底座</span><span className="mini-label">FULL-STACK / 01</span></div><div className="architecture-layer"><span className="layer-number">01</span><div><small>EXPERIENCE</small><strong>流暢的使用體驗</strong></div><span className="layer-icon"><Globe2 size={21} strokeWidth={1.4} /></span></div><div className="architecture-connector"><span />React.js<span className="tech-divider">/</span>Next.js<span className="tech-divider">/</span>TypeScript</div><div className="architecture-layer layer-active"><span className="layer-number">02</span><div><small>INTELLIGENCE & LOGIC</small><strong>貼合業務的智慧與流程</strong></div><span className="layer-icon"><BrainCircuit size={22} strokeWidth={1.4} /></span></div><div className="architecture-connector"><span />Python<span className="tech-divider">/</span>API<span className="tech-divider">/</span>AI Integration</div><div className="architecture-layer"><span className="layer-number">03</span><div><small>FOUNDATION</small><strong>安全可靠的數據與基礎設施</strong></div><span className="layer-icon"><Database size={21} strokeWidth={1.4} /></span></div><div className="architecture-footer"><span><Blocks size={14} />UML 架構先行</span><span><ShieldCheck size={14} />安全與效能並重</span></div><span className="architecture-detail" aria-hidden="true">DESIGNED WITH CLARITY. BUILT WITH PURPOSE.</span></div></div></section>

      <section className="section process-section" id="process" aria-labelledby="process-title"><div className="container"><div className="section-heading"><div><SectionLabel>HOW WE WORK TOGETHER</SectionLabel><h2 id="process-title">先理解你，再一起走。</h2></div><p className="section-description">你不需要帶著完整的規格書來。<br />帶著問題，我們一起找到答案。</p></div><ol className="process-grid">{[{ title: '聊清楚真正的問題', english: 'DISCOVER', description: '了解你的業務、現有流程與痛點，先確認甚麼值得解決。', deliver: '需求訪談・流程梳理' }, { title: '把想法變成可見方案', english: 'DEFINE', description: '以原型與架構釐清方向，對齊範圍、預算和驗收標準。', deliver: '方案建議・原型與 UML' }, { title: '小步實作，一起驗證', english: 'BUILD', description: '分階段開發與展示，讓使用者提早參與，及時調整。', deliver: '迭代開發・測試與回饋' }, { title: '安心上線，持續改善', english: 'EVOLVE', description: '完成部署、交接與培訓，按約定持續維運和優化。', deliver: '系統交付・培訓與支援' }].map((step, index) => <li className="process-step" key={step.english}><div className="process-top"><span className="process-number">0{index + 1}</span><span className="process-line" /><ArrowRight size={15} /></div><span className="mini-label">{step.english}</span><h3>{step.title}</h3><p>{step.description}</p><span className="process-deliver"><Check size={13} />{step.deliver}</span></li>)}</ol></div></section>

      <section className="section faq-section" id="faq" aria-labelledby="faq-title"><div className="container faq-grid"><div className="faq-heading"><SectionLabel>A LITTLE MORE CLARITY</SectionLabel><h2 id="faq-title">你可能也想知道。</h2><p>把疑問說清楚，<br />才是合作的好開始。</p><button disabled={!ready} className="text-link" onClick={() => openConsult()}>還有其他問題？聊聊吧<ArrowUpRight size={16} /></button><div className="faq-art" aria-hidden="true"><MessageSquareText size={47} strokeWidth={1} /><span>?</span><i /></div></div><div className="faq-list">{faqs.map((faq, index) => <details className="faq-item" key={faq.question}><summary><span className="faq-number">0{index + 1}</span><h3>{faq.question}</h3><Plus size={18} className="faq-plus" /></summary><div className="faq-answer"><p>{faq.answer}</p></div></details>)}</div></div></section>

      <section className="cta-section" aria-labelledby="cta-title"><div className="container"><div className="cta-panel"><div className="cta-copy"><SectionLabel>YOUR NEXT CHAPTER STARTS HERE</SectionLabel><h2 id="cta-title">下一個可能，<br />從一次對話開始。</h2><p>無論是第一個 AI 應用，還是下一階段的企業系統，<br className="desktop-break" />我們先聽你的想法。</p><button disabled={!ready} className="button button-navy" onClick={() => openConsult()}>預約免費諮詢<ArrowUpRight size={18} /></button><span className="cta-note">先了解需求，再決定下一步。</span></div><div className="cta-art" aria-hidden="true"><div className="cta-orbit cta-orbit-one" /><div className="cta-orbit cta-orbit-two" /><div className="cta-orbit cta-orbit-three" /><span className="cta-plus plus-a">+</span><span className="cta-plus plus-b">+</span><div className="cta-core"><svg viewBox="0 0 80 80" fill="none"><path d="M18 57L58 17M20 17h38v38" stroke="currentColor" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round" /></svg></div><span className="cta-art-caption">HUMAN IDEAS.<br /><strong>GREATER POSSIBILITIES.</strong></span></div></div></div></section>
    </main>
    {selectedService && <Modal title={selectedService.title} onClose={() => setSelectedService(null)}><span className="detail-category">{selectedService.english}</span><p className="modal-intro">{selectedService.detail}</p><h3 className="detail-subtitle">我們可以協助你</h3><ul className="detail-features">{selectedService.features.map(feature => <li key={feature}><CircleCheck size={18} />{feature}</li>)}</ul><div className="detail-fit"><strong>適合誰？</strong><p>{selectedService.fit}</p></div><p className="detail-note">實際功能、交付範圍、資料處理及服務承諾，將在需求評估後於合約中確認。</p><button className="button button-primary" onClick={() => { setSelectedService(null); openConsult(); }}>討論我的需求<ArrowUpRight size={17} /></button></Modal>}
  </>;
}
