import Link from 'next/link';
import { ArrowDown, ArrowUpRight, Check, CircleCheck } from 'lucide-react';
import type { ServiceCategory, ServiceDetail } from '@/lib/service-catalog';
import { ConsultButton } from './site-shell';
import { PageFAQ, PageSchema, PageProcess } from './page-blocks';
import { categoryIcons } from './catalog-icons';

const serviceFaqs = [
  { question: '這項服務如何報價？', answer: '報價按範圍、資料質素、整合難度、培訓及支援要求制定。免費諮詢後會提供方案與費用，進入實作前再確認詳細範圍。' },
  { question: '免費諮詢是否包括試做或培訓？', answer: '免費諮詢用於初步了解需求與方向，不等於免費開發、試點或正式培訓。實作、試點及培訓會另行報價。' },
];

export default function ServiceDetailPage({ category, service }: { category: ServiceCategory; service: ServiceDetail }) {
  const Icon = categoryIcons[category.icon];
  const siblings = category.services.filter(item => item.slug !== service.slug);
  return <><PageSchema title={`${service.title}｜${category.title}｜實瀚科技`} description={service.intro} path={`/services/${category.slug}/${service.slug}`} faqs={[...service.faqs, ...serviceFaqs]} breadcrumb={[{ name: '首頁', path: '/' }, { name: '解決方案', path: '/services' }, { name: category.title, path: `/services/${category.slug}` }, { name: service.title }]} /><main id="main" className="service-detail-page">
    <section className="service-detail-hero"><div className="container"><nav className="breadcrumbs" aria-label="麵包屑導覽"><Link href="/">首頁</Link><span aria-hidden="true">/</span><Link href="/services">解決方案</Link><span aria-hidden="true">/</span><Link href={`/services/${category.slug}`}>{category.title}</Link><span aria-hidden="true">/</span><span aria-current="page">{service.title}</span></nav><div className="service-detail-grid"><div><p className="hero-announcement"><span className="online-dot" />{service.english}</p><h1><span className="catalog-hero-icon"><Icon size={30} strokeWidth={1.4} /></span>{service.title}</h1><p className="detail-tagline">{service.tagline}</p><p className="catalog-lead">{service.intro}</p><div className="hero-actions"><ConsultButton /><a href="#capabilities" className="button button-secondary">了解解決方案<ArrowDown size={16} /></a></div></div><aside className="detail-hero-card"><span className="mini-label">AT A GLANCE</span><h2>它主要解決的問題</h2><p>{service.problem}</p><ul>{service.benefits.slice(0, 3).map(benefit => <li key={benefit}><Check size={14} />{benefit}</li>)}</ul></aside></div></div></section>
    <section className="section detail-benefit-section"><div className="container"><div className="detail-section-grid"><div><p className="section-label"><span />WHAT YOU GAIN</p><h2>它能為你帶來甚麼？</h2><p className="section-description">不是多一個工具，而是可衡量的工作改善。</p></div><ul className="detail-benefit-list">{service.benefits.map(benefit => <li key={benefit}><span className="benefit-check"><CircleCheck size={18} /></span><p>{benefit}</p></li>)}</ul></div></div></section>
    <section id="capabilities" className="section detail-capability-section"><div className="container"><div className="detail-section-grid"><div><p className="section-label"><span />WHAT WE CAN DO</p><h2>這項服務包含甚麼？</h2><p className="section-description">範圍會按你的實際需要組合，並非每次都全部採用。</p></div><div className="capability-grid">{service.capabilities.map(capability => <article className="capability-tile" key={capability}><span className="capability-tile-icon"><Icon size={19} strokeWidth={1.5} /></span><p>{capability}</p></article>)}</div></div></div></section>
    <section className="section detail-workflow-section"><div className="container"><div className="detail-section-grid"><div><p className="section-label"><span />HOW IT ROLLS OUT</p><h2>導入流程與節奏</h2><p className="section-description">先理解、再驗證、後接手，避免一次過投入造成風險。</p></div></div><PageProcess steps={service.workflow} /></div></section>
    <section className="section detail-fit-section"><div className="container"><div className="detail-section-grid"><div><p className="section-label"><span />WHO IT FITS</p><h2>它適合誰？</h2><p className="section-description">如果符合以下情況，這項服務對你較容易產生價值。</p></div><ul className="detail-fit-list">{service.fit.map(item => <li key={item}><Check size={14} />{item}</li>)}</ul></div></div></section>
    <PageFAQ items={[...service.faqs, ...serviceFaqs]} /><section className="cta-section solution-contact"><div className="container"><div className="cta-panel solution-cta"><div className="cta-copy"><p className="section-label"><span />TAKE THE NEXT STEP</p><h2>想了解{service.title}，<br />我們先聽你的想法。</h2><p>把問題說清楚，一起判斷這項服務是否適合，或需要結合其他能力。</p><ConsultButton className="button button-navy" /><span className="cta-note">初步諮詢免費；開發、試點及培訓另行評估報價。</span></div><aside className="contact-preparation"><span className="prep-icon"><Icon size={22} strokeWidth={1.4} /></span><h3>初步聯絡，可以先告訴我們</h3><ol>{category.checklist.map((item, index) => <li key={item}><span>0{index + 1}</span>{item}</li>)}</ol><p><Check size={14} />請勿附上個人資料、帳戶密碼或機密文件。</p></aside></div></div></section>
    <div className="container related-solutions"><span>同類其他解決方案</span><div>{siblings.map(item => <Link key={item.slug} href={`/services/${category.slug}/${item.slug}`}><span><strong>{item.title}</strong><small>{item.tagline}</small></span><ArrowUpRight size={17} /></Link>)}{siblings.length < 2 && <Link href={`/services/${category.slug}`}><span><strong>回到{category.title}</strong><small>查看此分類所有解決方案</small></span><ArrowUpRight size={17} /></Link>}</div></div><div className="solution-back-home"><Link href={`/services/${category.slug}`}>回到{category.title}<ArrowUpRight size={13} /></Link></div>
  </main></>;
}
