import Link from 'next/link';
import { ArrowDown, ArrowUpRight, BrainCircuit, Workflow, Database, Check, FileText, ShieldCheck, LockKeyhole, Command, UserRound, Layers3, GraduationCap, CircleCheck } from 'lucide-react';
import type { Solution } from '@/lib/solutions';
import { ConsultButton } from './site-shell';
import { Breadcrumbs, Eyebrow, PageCTA, PageFAQ, PageHeading, PageProcess, PageSchema, RelatedSolutions } from './page-blocks';

function WorkflowVisual({ data }: { data: Solution }) {
  const icons = [Database, BrainCircuit, ShieldCheck];
  const isSolo = data.slug === 'solo';
  const isEnterprise = data.slug === 'enterprise';
  return <div className={`solution-visual visual-${data.slug}`}><div className="solution-orbit orbit-outer" aria-hidden="true" /><div className="solution-orbit orbit-inner" aria-hidden="true" /><span className="solution-coordinate">{isSolo ? 'YOUR EVERYDAY, REIMAGINED.' : isEnterprise ? 'GOVERNANCE BY DESIGN.' : 'FROM INFORMATION TO ACTION.'}</span><div className="solution-workbench"><div className="workbench-bar"><span>{isSolo ? <UserRound size={16} /> : isEnterprise ? <LockKeyhole size={16} /> : <Command size={16} />}Hangs / {data.slug === 'sme' ? 'workflow' : isSolo ? 'my assistant' : 'enterprise'}</span><span className="demo-badge">概念示意</span></div><div className="workbench-content"><p className="mini-label">{isSolo ? 'YOUR PERSONAL WORKSPACE' : isEnterprise ? 'CONTROLLED INTELLIGENCE' : 'A MORE CONNECTED WAY TO WORK'}</p><h2>{data.workflow.title}</h2><div className="source-pills">{data.workflow.sources.map(source => <span key={source}>{source}</span>)}</div><div className="workbench-flow">{data.workflow.steps.map((step, index) => { const Icon = icons[index]; return <div key={step.title}>{index > 0 && <div className="workbench-connector" aria-hidden="true"><span /><ArrowDown size={12} /></div>}<div className={`workbench-step ${index === 1 ? 'intelligence-step' : ''}`}><span className="workbench-icon"><Icon size={21} strokeWidth={1.5} /></span><div><strong><span>0{index + 1}</span>{step.title}</strong><p>{step.text}</p></div>{index === 1 && <span className="online-dot" />}</div></div>; })}</div><div className="workbench-foot"><CircleCheck size={14} /><p>{data.workflow.foot}</p></div></div></div><div className="solution-floating-note">{isEnterprise ? <ShieldCheck size={19} /> : isSolo ? <BrainCircuit size={19} /> : <GraduationCap size={20} />}<span>{isEnterprise ? '清晰權責，穩健擴展' : isSolo ? '重要的決定，仍然由你掌握' : '不只交付系統，更交付能力'}<small>{isEnterprise ? 'BUILT FOR YOUR ORGANIZATION' : isSolo ? 'HUMAN FIRST. AI ASSISTED.' : 'BUILD IT. UNDERSTAND IT. OWN IT.'}</small></span><Check size={15} /></div></div>;
}

function ScenarioDiagram({ index, slug }: { index: number; slug: string }) {
  const labels = slug === 'sme' ? [['供應商資料', '報價草稿'], ['出貨文件', '異常清單'], ['內部文件', '知識查詢']] : slug === 'solo' ? [['會議筆記', '提案初稿'], ['品牌靈感', '內容大綱'], ['客戶查詢', '回覆草稿']] : [['授權文件', '來源答案'], ['業務事件', '審批流程'], ['版本變更', '受控部署']];
  return <div className={`scenario-diagram diagram-${index}`} aria-label={`${labels[index][0]}經 AI 輔助整理成${labels[index][1]}，概念示意`}><span className="diagram-node"><FileText size={19} strokeWidth={1.4} /><small>{labels[index][0]}</small></span><span className="diagram-line" /><span className="diagram-ai"><BrainCircuit size={25} strokeWidth={1.4} /></span><span className="diagram-line" /><span className="diagram-node"><Layers3 size={19} strokeWidth={1.4} /><small>{labels[index][1]}</small></span><span className="diagram-caption">ILLUSTRATIVE WORKFLOW</span></div>;
}

export default function SolutionPage({ data }: { data: Solution }) {
  const icons = [Workflow, BrainCircuit, Database];
  return <><PageSchema title={`${data.label} AI 解決方案`} description={data.description} path={`/solutions/${data.slug}`} faqs={data.faqs} /><main id="main" className={`solution-page solution-${data.slug}`}>
    <section className="solution-hero"><div className="container"><Breadcrumbs label={data.label} solution /><div className="solution-hero-grid"><div className="solution-hero-copy"><p className="hero-announcement"><span className="online-dot" />{data.eyebrow}</p><h1>{data.title[0]}<br /><span>{data.title[1]}<svg viewBox="0 0 420 18" preserveAspectRatio="none" aria-hidden="true"><path d="M4 12Q203 1 414 10" /></svg></span></h1><p className="solution-lead">{data.description}</p><div className="hero-actions"><ConsultButton /><a href="#solutions" className="button button-secondary">查看應用方向<ArrowDown size={16} /></a></div><p className="solution-hero-note"><Check size={13} />{data.note}</p></div><WorkflowVisual data={data} /></div><div className="solution-hero-bottom"><span>{data.english}</span><a href="#solutions">從你的工作開始<ArrowDown size={13} /></a></div></div></section>
    <div className="solution-promises"><div className="container">{data.promises.map(item => <span key={item}><Check size={14} />{item}</span>)}</div></div>
    <section id="solutions" className="section"><div className="container"><PageHeading eyebrow="START WITH THE REAL PROBLEM" title={data.pillarsTitle} intro={data.pillarsIntro} /><div className="solution-three-grid pillars-grid">{data.pillars.map((item, index) => { const Icon = icons[index]; return <article className="pillar-card" key={item.title}><div className="pillar-top"><span className="service-icon"><Icon size={25} strokeWidth={1.4} /></span><span className="mini-label">0{index + 1} / {item.label}</span></div><h3>{item.title}</h3><p>{item.text}</p><div className="pillar-result"><span>可由這些工作開始</span><strong>{item.examples}</strong></div></article>; })}</div></div></section>
    <section id="scenarios" className="section scenario-section"><div className="container"><PageHeading eyebrow="DESIGNED AROUND YOUR EVERYDAY" title={data.casesTitle} intro={data.casesIntro} /><div className="solution-three-grid">{data.cases.map((item, index) => <article className="scenario-card" key={item.industry}><ScenarioDiagram index={index} slug={data.slug} /><div className="scenario-card-body"><span className="scenario-industry">{item.industry}</span><h3>{item.title}</h3><p>{item.text}</p><ul>{item.points.map(point => <li key={point}><Check size={13} />{point}</li>)}</ul></div></article>)}</div><p className="solution-disclaimer">以上為應用示例，並非已完成客戶案例或成效保證。實際可行性、準確性及改善幅度，須按資料質素、系統限制與試點結果評估。</p></div></section>
    <section id="transfer" className="section transfer-section"><div className="container"><div className="transfer-panel"><div className="transfer-copy"><Eyebrow>BUILD CAPABILITY, NOT DEPENDENCY</Eyebrow><h2>{data.transferTitle[0]}<br /><span>{data.transferTitle[1]}</span></h2>{data.transferText.map(text => <p key={text}>{text}</p>)}<a href="#engagement" className="text-link">選擇適合的合作方式<ArrowUpRight size={16} /></a></div><div className="transfer-capabilities"><div className="transfer-panel-top"><span><GraduationCap size={17} />{data.slug === 'enterprise' ? '從治理到承接' : '讓能力留在你的團隊'}</span><small>THE HANGS APPROACH</small></div>{data.transfer.map((item, index) => <div className="transfer-capability" key={item.title}><span className="capability-number">0{index + 1}</span><div><h3>{item.title}</h3><p>{item.text}</p></div><CircleCheck size={18} /></div>)}<div className="transfer-panel-bottom"><ShieldCheck size={14} />可自行處理與需技術支援的範圍，清楚約定。</div></div></div></div></section>
    <section id="process" className="section solution-process-section"><div className="container"><PageHeading eyebrow="PROVE THE VALUE. THEN MOVE FORWARD." title={data.processTitle} intro={data.processIntro} /><PageProcess steps={data.steps} /></div></section>
    <section id="engagement" className="section engagement-section"><div className="container"><PageHeading eyebrow="A WAY OF WORKING THAT FITS YOU" title={data.modesTitle} intro={data.modesIntro} /><div className="solution-three-grid">{data.modes.map((mode, index) => <article className={`engagement-card ${index === 1 ? 'engagement-highlight' : ''}`} key={mode.title}><span className="engagement-label">{mode.label}</span><h3>{mode.title}</h3><p>{mode.text}</p><ul>{mode.points.map(point => <li key={point}><Check size={14} />{point}</li>)}</ul><div className="engagement-foot"><span>{mode.foot}</span><ConsultButton className="text-link">討論這個方向</ConsultButton></div></article>)}</div><div className="solution-tech-strip"><span>按需要選用技術，而非為了技術而技術</span><div>{data.technologies.map(tech => <span key={tech}>{tech}</span>)}</div></div></div></section>
    <PageFAQ items={data.faqs} /><PageCTA title={data.ctaTitle} text={data.ctaText} checklist={data.contactList} /><RelatedSolutions current={data.slug} /><div className="solution-back-home"><Link href="/">回到首頁<ArrowUpRight size={13} /></Link></div>
  </main></>;
}
