import { BrainCircuit, Workflow, Cloud, ShieldCheck, Code2, GraduationCap, Check, ArrowDown, Database, Layers3, ArrowUpRight } from 'lucide-react';
import Link from 'next/link';
import { ConsultButton } from '@/components/site-shell';
import { Breadcrumbs, Eyebrow, PageCTA, PageFAQ, PageHeading, PageProcess, PageSchema, RelatedSolutions } from '@/components/page-blocks';
import { pageMetadata } from '@/lib/metadata';

const description = '實瀚科技提供 AI 應用、自動化、雲端 DevOps、技術維運、資安檢測、客製系統、IoT 數據平台及實作培訓。從需求到交付，按你的業務選擇合適的技術。';
export const metadata = pageMetadata('解決方案｜AI、自動化與企業 IT 解決方案', description, '/services');
const offerings = [
  { icon: BrainCircuit, title: 'AI 應用與知識助手', slug: 'ai-applications', english: 'AI THAT WORKS FOR YOU', text: '從查詢、文件到企業知識，將 AI 變成可以融入工作流程的能力。先確認資料與品質要求，再決定模型及部署方式。', points: ['企業知識庫、RAG 與內部搜尋', '客服、銷售及行政 AI 應用', '文件分類、摘要與資料提取', 'AI Agent、API 與任務流程整合'] },
  { icon: Workflow, title: '工作流程與系統串接', slug: 'workflow-integration', english: 'LESS REPETITION. BETTER FLOW.', text: '找出工具之間重複搬運資料的步驟，透過合適的介面與工作流減少人手操作，保留審批與例外處理。', points: ['API、Webhook 及數據串接', 'RPA、審批與自動通知流程', '資料同步、定期彙整與報表', '執行紀錄、重試及異常跟進'] },
  { icon: Cloud, title: '雲端、DevOps 與技術維運', slug: 'cloud-devops', english: 'A STRONGER FOUNDATION.', text: '從上雲規劃到正式環境維護，讓架構、部署與觀測一起考慮。支援時段及維運責任按項目另行約定。', points: ['雲端遷移與基礎設施規劃', '容器部署、CI/CD 及自動化', '監控、備份與復原流程', '技術維運、培訓與駐場支援評估'] },
  { icon: ShieldCheck, title: '資訊安全檢測與防禦', slug: 'security', english: 'SECURITY WITH CLEAR BOUNDARIES.', text: '在獲授權的範圍內檢視風險，整理可落實的改善建議。把資料存取、權限與安全要求納入設計及維護。', points: ['授權範圍內的資安測試', '角色權限、存取與配置檢視', '弱點整改建議與防禦措施', '日誌、風險跟進與安全文件'] },
  { icon: Code2, title: '客製系統與數位平台', slug: 'digital-platforms', english: 'BUILT AROUND YOUR BUSINESS.', text: '當標準工具無法貼合業務，以清楚的架構與使用體驗設計客製方案。先定義流程與驗收，再分階段開發。', points: ['企業官網、電商與客戶平台', 'CRM、ERP 及內部管理系統', 'IoT 資料接入與大數據平台', 'React、Next.js 與全棧系統整合'] },
  { icon: GraduationCap, title: '實作培訓與技術轉移', slug: 'training', english: 'KEEP THE CAPABILITY WITH YOU.', text: '以真實工作設計教材與實作，讓指定同事不只學會操作，也理解流程、可調整範圍與技術限制。', points: ['AI、Agent 與自動化實作', '按需要教授 Python、MCP 與 API', '操作文件、實作練習及交接', '共同開發與獨立操作能力檢查'] },
];
const faqs = [
  { question: '需要先選定服務或技術，才可以諮詢嗎？', answer: '不需要。你可以先說明目前的工作方式、最想改善的問題及使用工具。我們會判斷是否需要開發、串接、自動化或培訓；如果現成工具已足夠，也不預設必須客製開發。' },
  { question: '可以只委託一項服務，而不是整套系統嗎？', answer: '可以。可按需求評估單一工作流程、AI 助手設定、技術檢視、專項開發或培訓。前提是範圍、資料來源、相關系統責任與驗收方式足夠清楚。' },
  { question: '服務費是否包括第三方平台及長期維護？', answer: '報價會列明開發、配置、培訓、雲端、模型用量及第三方訂閱的包含範圍。長期維護、駐場或 SLA 通常按需求另行約定，並不預設所有服務都包含永久支援。' },
  { question: '系統完成後會提供哪些交付文件？', answer: '視服務範圍，可包括需求與架構說明、部署設定、測試與驗收紀錄、操作手冊及技術交接。源碼、帳號、第三方授權與知識產權安排，會在合作前以合約列明。' },
  { question: '免費諮詢是否包括免費試點或培訓？', answer: '免費諮詢主要用於初步了解需求及討論可能方向，不等於免費開發、試點、資安測試或正式培訓。進入實作前會另行確認範圍、費用及交付要求。' },
];

export default function ServicesPage() {
  return <><PageSchema title="AI、自動化與企業 IT 解決方案" description={description} path="/services" faqs={faqs} /><main id="main" className="services-page">
    <section className="services-page-hero"><div className="container"><Breadcrumbs label="解決方案" /><div className="services-intro-grid"><div><Eyebrow>OUR SERVICES / FROM IDEA TO EVERYDAY</Eyebrow><h1>讓技術各司其職，<br /><span>讓業務真正向前。</span></h1><p>從第一個 AI 助手，到企業級數位平台。<br />我們不以工具定義服務，而是以你需要解決的問題，決定如何設計、落實與交付。</p><div className="hero-actions"><ConsultButton /><a href="#overview" className="button button-secondary">了解解決方案<ArrowDown size={16} /></a></div></div><div className="services-network" aria-label="以業務需求連接設計、技術、交付及支援的示意圖"><div className="network-orbit" /><div className="network-orbit network-orbit-two" /><div className="network-center"><Layers3 size={30} strokeWidth={1.3} /><strong>你的業務需求</strong><small>THE STARTING POINT</small></div><span className="network-node node-ai"><BrainCircuit size={20} />AI 與自動化</span><span className="network-node node-cloud"><Cloud size={20} />雲端與維運</span><span className="network-node node-code"><Code2 size={20} />系統與平台</span><span className="network-node node-security"><ShieldCheck size={20} />安全與治理</span><span className="network-caption">CONNECTED BY PURPOSE, NOT COMPLEXITY.</span></div></div><div className="services-intro-foot"><span>一個技術夥伴，串起從需求到維運的每一步。</span><span>AI · AUTOMATION · CLOUD · PLATFORMS</span></div></div></section>
    <section id="overview" className="section service-overview"><div className="container"><PageHeading eyebrow="WHAT WE CAN BUILD TOGETHER" title={['從你的需求出發，', '組合真正需要的能力。']} intro="實際方案可結合多項能力。先了解你的工作方式、資料與系統限制，再決定值得投入的技術及交付範圍。" /><div className="service-offerings">{offerings.map((item, index) => <article className="offering-row" key={item.title}><div className="offering-identity"><span className="offering-number">0{index + 1}</span><span className="service-icon"><item.icon size={27} strokeWidth={1.4} /></span></div><div className="offering-description"><span className="mini-label">{item.english}</span><h3>{item.title}</h3><p>{item.text}</p><Link href={`/services/${item.slug}`} className="offering-more">查看解決方案詳情<ArrowUpRight size={15} /></Link></div><ul>{item.points.map(point => <li key={point}><Check size={14} />{point}</li>)}</ul><span className="offering-decoration" aria-hidden="true"><ArrowUpRight size={22} strokeWidth={1} /></span></article>)}</div></div></section>
    <section id="delivery" className="section service-delivery"><div className="container"><div className="delivery-grid"><div><Eyebrow>CLARITY IS PART OF THE DELIVERY</Eyebrow><h2>交付的不只是功能，<br />還有清楚的下一步。</h2><p>工具是否好用、團隊是否接得住、出現問題誰負責，都應在合作中被說清楚。</p><ConsultButton className="text-link">討論你的交付要求</ConsultButton></div><div className="delivery-checklist">{[{ icon: Layers3, title: '範圍清楚', text: '需求、交付內容、時程與驗收方式先確認。' }, { icon: Database, title: '權責清楚', text: '資料、帳號、源碼、授權及平台費用按約定列明。' }, { icon: GraduationCap, title: '交接清楚', text: '操作指引、實作培訓及可自行修改的範圍。' }, { icon: ShieldCheck, title: '支援清楚', text: '維護內容、服務時段、回應標準與變更安排。' }].map(item => <article key={item.title}><item.icon size={22} strokeWidth={1.4} /><div><h3>{item.title}</h3><p>{item.text}</p></div><Check size={16} /></article>)}</div></div></div></section>
    <section className="section"><div className="container"><PageHeading eyebrow="A PRACTICAL WAY FORWARD" title={['不必帶著規格書來，', '帶著問題就可以。']} intro="先確認值得做甚麼，再決定怎樣做。免費初步諮詢與付費實作的範圍，會清楚區分。" /><PageProcess steps={[{ title: '了解需求', text: '討論業務目標、現有工具與最想改善的工作。', output: '問題與初步方向' }, { title: '定義方案', text: '釐清範圍、介面、資料要求及可衡量的驗收標準。', output: '方案與報價' }, { title: '實作與驗證', text: '按約定分階段開發、展示及測試，必要時先做付費試點。', output: '可驗證的成果' }, { title: '交接與支援', text: '完成部署、教學與文件，再按需要安排持續支援。', output: '正式交付與承接' }]} /></div></section>
    <PageFAQ items={faqs} /><PageCTA title={['不確定需要哪種服務？', '先聊你想改善的事。']} text="不用先選技術，也不用先決定開發多少功能。讓我們一起把問題說清楚，再找到適合你的起步方式。" checklist={['業務類型與團隊規模', '最想解決的一項問題', '現有工具、系統與限制', '期待的結果及內部參與人員']} /><RelatedSolutions />
  </main></>;
}
